### PR TITLE
[modular] adds a fox tail organ sprite, adds fox tails to limbgrowers

### PR DESCRIPTION
**Pull request by Gofawful5**
this adds a unique fox tail organ sprite that can be seen when it's cut off / grown
and also adds onto the limbgrower's **Other** category when xeno organs are researched

changes dependent on hair color because yknow:

image

image

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
Conflicts + you should really just gags this if you're gonna make a strictly orange one

**Comment by Jolly-66** [comment]
I'm going to close future PRs if I see captracy

**Comment by Gofawful5** [comment]
> I'm going to close future PRs if I see captracy

cry

**Review by MrMelbert — COMMENTED** [review]
Maybe just add the fox tails to the felinid design disk instead of its own disk? Unless you plan on adding more organs to the disk later

**Comment by Gofawful5** [comment]
> Maybe just add the fox tails to the felinid design disk instead of its own disk? Unless you plan on adding more organs to the disk later

i was thinking about making fox ears a thing at some point, yeah
I'll add it onto the felinid disk for now though

**Pull request merged**
