### PR TITLE
Adds in Green Tea and 2 "descendant" drinks.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
This PR adds in Green Tea, alongside two drinks made from it.

How to make Green Tea:
Get some fresh tea leaves from botany. (You cannot synthesize or buy this!)
Dry them.
Grind them to tea powder.
Mix tea powder in a 1-5 ratio with water.
You now have Green Tea, which for gameplay purposes, is a decent anti-toxin with no downsides. It also happens to be straight up better than black tea, because gameplay. (and in real life too and if you dont agree i will beat you to death)

How to make Iced Green Tea:
Just mix some ice!

How to make Green Hill Tea:
A special green tea blend, it looks like green flowing hills on checkerboarded dirt.
To obtain it, you must mix Iced Green Tea and Sugar Rush in a 1-1 ratio. Upon doing so, you obtain a drink that loses the anti-toxin and other features of regular Green Tea, however the new beverage makes you slightly faster.

Do not overdose on it.

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
ps: dont tell anyone but there's a secret (broken) unused version of green tea in a cup

**Comment by Jolly-66** [comment]
>Files changed; 43

What the fuck did you do?

**Comment by CRITAWAKETS** [comment]
wait what the fuck why did it just delete all those files

**Comment by Jolly-66** [comment]
image

pls resubmit the pr and just nuke these files they've been creating issues from the gecko

**Comment by CRITAWAKETS** [comment]
finally. fixes.

**Review by MrMelbert — COMMENTED** [review]
Code LGTM, I just ask that you test a variety of non-module drinks to make sure your changes to the icon files don't affect them.

**Comment by CRITAWAKETS** [comment]
> Code LGTM, I just ask that you test a variety of non-module drinks to make sure your changes to the icon files don't affect them.


ye

**Comment by Jolly-66** [comment]
Since I was barely following along in #coding-general can you explain what you done did in the main drinks file?

**Comment by CRITAWAKETS** [comment]
> Since I was barely following along in #coding-general can you explain what you done did in the main drinks file?

Drinks now point to our own modular drinks file, as there is no way to set the individual glass icon searching area for reagents.

**Pull request merged**
